"""
Django settings for miproyecto_CCR project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import pymysql
from decouple import config, Csv


# =========================================================
# PYMysql
# =========================================================

# Hace que Django use PyMySQL como controlador de MySQL
pymysql.install_as_MySQLdb()


# =========================================================
# RUTAS DEL PROYECTO
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# CONFIGURACIÃ“N GENERAL
# =========================================================

# La SECRET_KEY se obtiene desde .env en desarrollo
# y desde las variables de entorno en Render.
SECRET_KEY = config('SECRET_KEY')

# En desarrollo puede ser True.
# En Render debe configurarse como False.
DEBUG = config('DEBUG', default=False, cast=bool)

# Hosts permitidos.
# Ejemplo local:
# ALLOWED_HOSTS=localhost,127.0.0.1
#
# En Render:
# ALLOWED_HOSTS=nombre-del-servicio.onrender.com
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv()
)


# =========================================================
# APLICACIONES
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # AplicaciÃ³n del proyecto
    'core',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise debe ir inmediatamente despuÃ©s
    # de SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URLS
# =========================================================

ROOT_URLCONF = 'miproyecto_CCR.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'miproyecto_CCR.wsgi.application'


# =========================================================
# BASE DE DATOS
# =========================================================

# ConexiÃ³n con MySQL/Aiven.
# Los datos se obtienen del archivo .env localmente
# o de las variables de entorno configuradas en Render.

DATABASES = {
    'default': {

        # Motor MySQL
        'ENGINE': 'django.db.backends.mysql',

        # Nombre de la base de datos
        'NAME': config('DB_NAME'),

        # Usuario
        'USER': config('DB_USER'),

        # ContraseÃ±a
        'PASSWORD': config('DB_PASSWORD'),

        # Host de Aiven
        'HOST': config('DB_HOST'),

        # Puerto de Aiven
        'PORT': config('DB_PORT', default='3306'),

        # ConexiÃ³n SSL requerida por Aiven
        'OPTIONS': {
            'ssl': {
                'ssl-mode': 'REQUIRED',
            }
        },
    }
}


# =========================================================
# VALIDACIÃ“N DE CONTRASEÃ‘AS
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNACIONALIZACIÃ“N
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# ARCHIVOS ESTÃTICOS
# =========================================================

# URL para CSS, JavaScript, imÃ¡genes, etc.
STATIC_URL = '/static/'

# Carpeta donde collectstatic recopila todos
# los archivos estÃ¡ticos antes de publicar.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# =========================================================
# WHITENOISE
# =========================================================

# WhiteNoise comprime y versiona los archivos estÃ¡ticos
# para poder servirlos correctamente en producciÃ³n.

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },

    'staticfiles': {
        'BACKEND':
        'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# =========================================================
# EMAIL
# =========================================================

# Durante desarrollo los correos se muestran
# directamente en la consola.

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
